// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXJHgckUorS4u6smK2iJjxaijOXgSa1R4',
    appId: '1:653291352238:web:3a588bda8a7b965f8c3d3f',
    messagingSenderId: '653291352238',
    projectId: 'vobiss-app',
    authDomain: 'vobiss-app.firebaseapp.com',
    storageBucket: 'vobiss-app.appspot.com',
    measurementId: 'G-GVTCGT0DS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKxmPrxRjbnnIG-lTvXjqWllKCc7ZQxRI',
    appId: '1:653291352238:android:39e382dfee7d9b1a8c3d3f',
    messagingSenderId: '653291352238',
    projectId: 'vobiss-app',
    storageBucket: 'vobiss-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXV2Da102oVfFXYv8TVjcbdgijg-htLcU',
    appId: '1:653291352238:ios:40925e485033e3b68c3d3f',
    messagingSenderId: '653291352238',
    projectId: 'vobiss-app',
    storageBucket: 'vobiss-app.appspot.com',
    iosBundleId: 'com.ivan.vobissApp',
  );
}
